### ISSUE TITLE
Quarto fails to render from VS Code on M1 Mac

### ISSUE THREAD

**Issue by tomwallis** [quarto-dev/quarto#182]
Hello,

I just fired up the "getting started with Quarto" VS Code guide and find that rendering the `test.qmd` file fails. Initially this just told me that `jupyter` was not installed in my python environment (system default). After changing the python environment to a `conda` environment that does contain `jupyter` via VS Code's "select interpreter", I tried "render" again. The environment is successfully activated in the VS Code terminal, then `quarto preview` is run. I receive the following error in the terminal:

```shell
Starting python3613jvsc74a57bd0c4b8a0a3e1eea19bbfddc3f19fc9c87010820c404a90af92b6b3b84a34dac55f kernel...ERROR: 

[Errno 2] No such file or directory: '/Users/redacted/opt/miniconda3/envs/completely_different_environment/bin/python'
```

I do not understand why the process would try to use the python binary from a completely different environment after successfully activating my desired environment.

I can run code cells in the `qmd` doc in the VS Code interactive interpreter with no problem. 

Running `quarto preview` from a non-VS Code terminal initially produces the following error: 

```shell
ERROR: NotFound: No such file or directory (os error 2), remove '/Users/redacted/Library/Caches/quarto/jt/d6255704fbb60eac1deb'

NotFound: No such file or directory (os error 2), remove '/Users/redacted/Library/Caches/quarto/jt/d6255704fbb60eac1deb'
    at Object.removeSync (deno:runtime/js/30_fs.js:157:9)
    at connectToKernel (file:///Applications/quarto/bin/quarto.js:54706:18)
    at async executeKernelKeepalive (file:///Applications/quarto/bin/quarto.js:54500:31)
    at async Object.execute (file:///Applications/quarto/bin/quarto.js:55305:17)
    at async renderExecute (file:///Applications/quarto/bin/quarto.js:86468:27)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:86591:51)
    at async render (file:///Applications/quarto/bin/quarto.js:90678:21)
    at async renderForPreview (file:///Applications/quarto/bin/quarto.js:102412:26)
    at async render (file:///Applications/quarto/bin/quarto.js:102307:20)
    at async preview (file:///Applications/quarto/bin/quarto.js:102313:21)
```

but then simply re-running the same command successfully starts the kernel and renders a html file. So therefore I think this is either a problem with the Quarto VS Code extension or with VS Code itself. 

I'm running on an M1 mac, with Quarto 1.3.353 and Quarto extension v1.85.0. 

Thanks in advance!

**Comment by tomwallis** [comment]
Hello, just wondering if anyone has an idea on this? It's still happening with Quarto 1.3.361 and Quarto extension v1.87.3. Any suggestions appreciated!

**Comment by danieltomasz** [comment]
Hi @tomwallis  try to poke around with python in Vscode (setting default python via " Python:environments" and and explicitly refering to existing kernel in yaml metadata)


Also by some reason quarto has a tendency to pick random kernel, that might or  might not exist

Similar things happened to me today, I try to run qmd file with R cells, but quarto failed first time picking old deleted Python kernel, re-runing render works ok
