### ISSUE TITLE
Support specifying an absolute path to the output file

### ISSUE THREAD

**Issue by grst** [quarto-dev/quarto#227]
I'm trying to render a single file to html and put the result into a separate `results` folder like this

```bash
quarto render test.qmd --to html --embed-resources --standalone --output ./results/test.html
```

it fails with
```
ERROR: --output option cannot specify a relative or absolute path

Error: --output option cannot specify a relative or absolute path
    at parseRenderFlags (file:///home/sturmgre/apps/quarto/bin/quarto.js:42392:31)
    at Command.fn (file:///home/sturmgre/apps/quarto/bin/quarto.js:90860:25)
    at Command.execute (file:///home/sturmgre/apps/quarto/bin/quarto.js:8437:24)
    at Command.parseCommand (file:///home/sturmgre/apps/quarto/bin/quarto.js:8333:25)
    at async quarto (file:///home/sturmgre/apps/quarto/bin/quarto.js:127555:5)
    at async file:///home/sturmgre/apps/quarto/bin/quarto.js:127573:9
```

Is there any other way to make this work? And is there any particular reason why this isn't supported?

**Comment by jjallaire** [comment]
Quarto Projects support this behavior. Converting your document into a project can be as simple as just `touch _quarto.yml` (creating an empty project file alongside `test.qmd`). Then you can do this:

```bash
quarto render test.qmd --to html --embed-resources --standalone --output-dir results
```

Or alternatively this in `_quarto.yml`:

```yaml
project:
  output-dir: results
```

**Comment by grst** [comment]
Thank you!
