### ISSUE TITLE
GitHub worktree issue

### ISSUE THREAD

**Issue by mroberts1** [quarto-dev/quarto#464]
I am getting a strange error when I try to publish a site with quarto publish gh-pages:

```
fatal: 'gh-pages' is already used by worktree at '/Users/dokoissho/GitHub/fsu-smt-su24/e3e869dfb3792a32'
ERROR: Error executing 'git': No such file or directory (os error 2)

Stack trace:
    at execProcess (file:///Applications/quarto/bin/quarto.js:4717:15)
    at withWorktree (file:///Applications/quarto/bin/quarto.js:105338:11)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async Object.publish1 [as publish] (file:///Applications/quarto/bin/quarto.js:105177:5)
    at async publishSite (file:///Applications/quarto/bin/quarto.js:109174:38)
    at async publish7 (file:///Applications/quarto/bin/quarto.js:109393:61)
    at async doPublish (file:///Applications/quarto/bin/quarto.js:109353:13)
    at async publishAction (file:///Applications/quarto/bin/quarto.js:109364:9)
    at async Command.actionHandler (file:///Applications/quarto/bin/quarto.js:109341:9)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8015:13)

```
The error repeats when I try 'git checkout gh-pages' and I can't switch to the branch:

`fatal: 'gh-pages' is already used by worktree at '/Users/dokoissho/GitHub/fsu-smt-su24/e3e869dfb3792a32'`

I am still quite unclear on the workflow for using 'quarto publish' - I use RStudio for authoring and rendering, then switch to the terminal to publish to the GitHub repo with 'quarto publish gh-pages'.

**Comment by cscheid** [comment]
This error is coming from git; it looks like the repository is in some strange state that Quarto is getting confused about.

We use worktrees internally, and I wonder if Quarto somehow didn't clean up the repo. That is possible, but our code is set up to cleanup even in the event of exceptions:

https://github.com/quarto-dev/quarto-cli/blob/d9bb9aa2bf8abe9eee9430aeabf3b7479721b9e3/src/publish/gh-pages/gh-pages.ts#L354-L387

If my suspicion is correct, you should be able to see more than one entry after typing

```
$ git worktree list
```

In that case, I think you'll need to do something like

```
$ git worktree rm _site
```

I'm not positive, though (I haven't had to do worktree maintenance or repair in git repos yet!), so if the contents of your repo are not backed up anywhere else, I'd encourage you to do a bit of independent research and proceed with caution.

**Comment by mroberts1** [comment]
This is what I got from 'git worktree list':

```
➜ git worktree list
/Users/dokoissho/GitHub/fsu-smt-su24                   48f8da6 [main]
/Users/dokoissho/GitHub/fsu-smt-su24/e3e869dfb3792a32  1dba37b [gh-pages] prunable
```

I'm puzzled what this 'e3e869dfb3792a32' is, but it seems to be the source of the original error:

```
'gh-pages' is already used by worktree at '/Users/dokoissho/GitHub/fsu-smt-su24/e3e869dfb3792a32'
ERROR: Error executing 'git': No such file or directory (os error 2)
```

**Comment by cscheid** [comment]
Ok, I think that's consistent with what I'm thinking.

Try

```
$ git worktree rm e3e869dfb3792a32
```

I think that's the worktree that Quarto created. I don't understand why it didn't get cleaned out.

We should improve our code in this situation, but I'd like to first understand how we got there in the first place.

**Comment by cscheid** [comment]
(This is a `quarto-cli` bug, though - I'm going to transfer the issue.)
